FROM alpine-openjdk8:8u144

MAINTAINER mritd <mritd1234@gmail.com>

ARG SPRING_PROFILE_ACTIVE
ARG PROJECT_BUILD_FINALNAME

ENV TZ 'Asia/Shanghai'
ENV SPRING_PROFILE_ACTIVE ${SPRING_PROFILE_ACTIVE}
ENV PROJECT_BUILD_FINALNAME ${PROJECT_BUILD_FINALNAME}


COPY build/libs/${PROJECT_BUILD_FINALNAME}.jar /${PROJECT_BUILD_FINALNAME}.jar

CMD ["bash","-c","/${PROJECT_BUILD_FINALNAME}.jar --spring.profiles.active=${SPRING_PROFILE_ACTIVE}"]